name: Manually trigger an Azure Machine Learning job

on:
  workflow_dispatch:

jobs:
  experiment:
    environment: development
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Jobs AML
      run: |
        az ml job create --file job.yml  
        --resource-group diabetes-dev-rg 
        --workspace-name aml-diabetes-dev
  production:
    environment: production
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Jobs AML
      run: |
        az ml job create --file job2.yml  
        --resource-group diabetes-dev-rg 
        --workspace-name aml-diabetes-dev   




