name: verification

on: 
    pull_request:
        types: opened
jobs:
    job1:
        name: echo
        runs-on: ubuntu-latest
        steps:
        - name: test
          run: |
                echo "Will add code checks here in next challenge"